# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67ffd3a2252a1e8b74d7e45f769e20700f0eac5783590bc0da6b0dedbd6c817e8ac64913212db4215598c536ae39f0c8a360899db71121182c3420df8e35ec32

test:
  secret_key_base: 17c2cd635cd1d9dbac40ca6df041d046491b7244e005703ce1086e8982d8983d97a249224626084661432ab4266336c81dcb13bf674349197f5f264db407bf9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
